### PR TITLE
added google drive for projects

### PR DESCRIPTION
**Pull request by Will15800**
I implemented functionality to display the project's Google Drive folder in a list/grid view and added a button to go to the drive page. Since there is no individual project page yet, I will add it to the project page later. Please let me know if there are any issues/problems.

### CODE REVIEW

**Comment by RichardSima2021** [comment]
What is the commented getDriveFiles() for?

**Comment by RichardSima2021** [comment]
Can you create a demo page to show it please?

**Comment by Will15800** [comment]
I have created the demo page at [http://localhost:3000/folder](url), and deleted the getDriveFiles code (not useful). Thanks!

**Comment by RichardSima2021** [comment]
Looks good to me, thanks Will!

**Pull request merged**
